w4/mymusicapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  shallow do
    resources :bands do
      resources :albums, only: [:new, :index] do
        resources :tracks, only: [:new, :index]
      end
    end
  end
end

w4/mymusicapp/app/models/album.rb
class Album < ApplicationRecord

  has_many :tracks,
  class_name: :Track,
  primary_key: :id,
  foreign_key: :track_id,
  dependent: :destroy

  belongs_to :band,
  class_name: :Band,
  primary_key: :id,
  foreign_key: :album_id
end

w4/mymusicapp/app/models/band.rb
class Band < ApplicationRecord

  has_many :albums,
  class_name: :Album,
  primary_key: :id,
  foreign_key: :album_id,
  dependent: :destroy
end

w4/mymusicapp/app/models/track.rb
class Track < ApplicationRecord

  belongs_to :album,
  class_name: :Album,
  primary_key: :id,
  foreign_key: :track_id,
end

w4/mymusicapp/app/models/user.rb
class User < ApplicationRecord

  validates :email, :password_digest, presence: true
  validates :email, uniqueness: true
  validates :password, length: { minimum: 6 }

  after_initialize :ensure_token

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def password
    @password
  end

  def password=(password)
    @password = password
    digest = BCrypt::Password.create(password)
    self.password_digest = digest
  end

  def is_password?(password)
    pass = BCrypt::Password.new(password)
    pass.is_password?(self.password_digest)
  end

  def generate_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    user if user && user.is_password?(password)
  end

end

w4/mymusicapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
end

w4/mymusicapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :log_in_user!

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    return false if @current_user.nil?
    @current_user.session_token == session[session_token]
  end

  def log_in_user!(user)
    @current_user = @user
    session[:session_token] = @current_user.session_token
  end
end

w4/mymusicapp/app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save!
      redirect_to band_url(@band.id)
    else
      render :new
    end
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

w4/mymusicapp/app/controllers/session_controller.rb
class SessionController < ApplicationController
	
	def new
		render :new
	end
	
	def create
		@user = User.find_by_credentials(user_params[:email], user_params[:password])
		if @user
			session[:session_token] = user.session_token
			redirect_to #music page
		else
			redirect_to new_session_url
		end
	end
	
	def destroy
		@user.reset_session_token!
		redirect_to new_session_url
	end
	
	private
	
	def user_params
		@params.require(:user).permit(:email, :password)
	end
end

w4/mymusicapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		render :new
	end

	def create
		@user = User.find_by_credentials(user_params[:email], user_params[:password])
		if @user
			session[:session_token] = user.session_token
			redirect_to user_url
		else
			render :new
		end
	end

	def destroy
		current_user.reset_session_token!
		redirect_to new_session_url
	end

	private

	def user_params
		params.require(:user).permit(:email, :password)
	end
end

w4/mymusicapp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
end

w4/mymusicapp/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			log_in_user!(@user)
			redirect_to user_url(id: @user.id)
		else
			render :new
		end
	end

	def user_params
		params.require(:user).permit(:email, :password)
	end

end

w4/mymusicapp/app/helpers/session_helper.rb
module SessionHelper
end

w4/mymusicapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mymusicapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<h>
  <% unless current_user.nil? %>
    <%= button_to "logout", session_url, method: :destroy %>
  <% else %>
    <%= link_to "sign in", new_session_url %>
    <%= link_to "sign up", new_user_url %>
  <% end %>
</h>
<br>
<br>

  <body>
    <%= yield %>
  </body>
</html>

w4/mymusicapp/app/views/session/new.html.erb
<h>Login</h>
<form action="<%session_url%>" method="post">
	<label for="email_label">Email:</label>
	<input type="text"
				 name="user[email]"
				 id="email_label"
				 value="<%@user.email%>">
	<br>
	<label for="password_label">Password:</label>
	<input type="password"
				 name="user[password]"
				 id="password_label"
				 value="<%@user.password%>">
	<br>
	<input type="submit">
</form>

w4/mymusicapp/app/views/users/new.html.erb
<h> Welcome to MyMusicApp! </h>
<h2> Signup </h2>
<form action="<%=users_url%>" method = "post">
	<label for="email_label">Email:</label>
	<input type="text"
				 name="user[email]"
				 id="email_label"
				 value="<%= @user.email %>">
	<br>
	<label for="password_label">Password:</label>
	<input type="password"
				 name="user[password]"
				 id="password_label">
	<br>
	<input type="submit" value="Signup">
</form>

w4/mymusicapp/app/views/users/show.html.erb
<h> Welcome, <%= current_user.email %>! </h>